### ISSUE TITLE
Preparar un ejemplo del planificador global en C++ para AIRBUS

### ISSUE THREAD

**Issue by carlibiri** [spaceuma/ARES-DyMu_python#3]
Lo comentamos mañana Jueves, pero la idea que tengo es que les pasemos las librerías en C++/Python. Ellos están interesados especialmente en C++. Entonces podríamos generar un proyecto en C+ de ejemplo con un main que cargue un mapa de costes y genere el camino para ir de un punto a otro. De esta manera sería más fácil para ellos poder testearlo e integrarlo.

**Comment by JRicardoSan** [comment]
Sí, pienso también que un main en un test sería suficiente para demostrar cómo funciona. También llevo tiempo pensando que el repositorio del planner debería tener una manera para que esté también autocontenida y no dependa de rock, no llevaría mucho.
Al repo de python aún le falta implementar de alguna manera el local repairing, pero si de momento únicamente quieren el global entonces perfe (de hecho, en cuanto pueda quiero dejarlo con la estructura de un paquete de python al igual que estoy haciendo con el de camis). Lo vemos mañana.

**Comment by JRicardoSan** [comment]
Link a la release:
https://github.com/esa-prl/planning-path_planning/releases/tag/v1.0
Link al repositorio:
https://github.com/esa-prl/planning-path_planning/tree/standalone_ver
