### ISSUE TITLE
Prueba de FM-shadowing

### ISSUE THREAD

**Issue by carlibiri** [spaceuma/ARES-DyMu_python#4]
Realizar una simulación sencilla para comprobar si el vehículo llegaría con una orientación deseada y a una distancia de seguridad de los obstáculos alrededor de la muestra.

**Comment by carlibiri** [comment]
Se comprueba que el cono no funciona, y Ricardo propone emplear shadowing para hacer que el vehículo vaya encarando a la muestra. @JRicardoSan realiza unas pruebas en simulación.

**Comment by carlibiri** [comment]
![20191205_133218](https://user-images.githubusercontent.com/7371595/70699174-02d8fa80-1cc9-11ea-91bd-38f3f5b7ca86.jpg)

**Comment by carlibiri** [comment]
Pendiente pasar a C++

**Comment by JRicardoSan** [comment]
Como la prueba ya se hizo en python, voy a cerrar este issue aquí y crear otro asociado al repositorio de ADE para la implementación en C++.
